// Prerender: runs the same render functions as assets/js/main.js against data/*.json
// and writes fully populated HTML to index.html, so crawlers and link previews
// (LinkedIn, Slack, WhatsApp, ATS tools) see real content without running JavaScript.
// The browser still runs main.js, which re-renders the same content and wires up interactivity.
//
// Edit src/index.html and data/*.json, then run: npm run build
import { readFile, writeFile } from 'node:fs/promises';
import { JSDOM } from 'jsdom';

const root = new URL('../', import.meta.url);
const template = await readFile(new URL('src/index.html', root), 'utf8');
const mainJs = await readFile(new URL('assets/js/main.js', root), 'utf8');

const dom = new JSDOM(template, { url: 'https://akashdeore.com/', runScripts: 'outside-only' });
const { window } = dom;

window.fetch = async (path) => {
  const body = await readFile(new URL(String(path).replace(/^\//, ''), root), 'utf8');
  return { ok: true, json: async () => JSON.parse(body), text: async () => body };
};
window.matchMedia = () => ({ matches: true, addListener() {}, removeListener() {} });

// Load the render functions without triggering the browser-only init (particles, scroll effects).
window.eval(mainJs.replace("document.addEventListener('DOMContentLoaded'", "void (0) && document.addEventListener('DOMContentLoaded'"));

const errors = [];
window.console.error = (...args) => errors.push(args.join(' '));

await window.eval(`Promise.all([
  loadSiteConfig(), loadNavigation(), loadHero(), loadAbout(), loadExperience(),
  loadSkills(), loadProjects(), loadEducation(), loadContact(), loadFooter()
])`);

if (errors.length) {
  console.error('Prerender failed:\n' + errors.join('\n'));
  process.exit(1);
}

const banner = '<!-- GENERATED by scripts/prerender.mjs. Edit src/index.html and data/*.json, then run `npm run build`. -->\n';
await writeFile(new URL('index.html', root), banner + dom.serialize() + '\n');
console.log('index.html prerendered');
